gatling {
  core {
    outputDirectoryBaseName = "gatling-results"
    runDescription = "OAS Demo API Performance Test"
    encoding = "utf-8"
    simulationClass = ""

    directory {
      simulations = ""
      resources = "src/gatling/resources"
      results = "build/reports/gatling"
      binaries = ""
    }
  }

  charting {
    indicators {
      lowerBound = 100
      higherBound = 500
      percentile1 = 50
      percentile2 = 75
      percentile3 = 95
      percentile4 = 99
    }
  }

  http {
    warmUpUrl = "http://localhost:8080/hello"

    ssl {
      useOpenSsl = false
    }
  }

  data {
    writers = [console, file]
  }
}
