spring.datasource.url=jdbc:h2:mem:bookstore
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false

app.seeding.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/bookstore/protocol/openid-connect/certs
